version: "3"

services:

  # Nginx & SSL
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  # Microservices
  apigateway:
    image: lucasignacio18/fakebook/apigateway-1.0
    restart: unless-stopped
    env_file:
      - docker/services/apigateway.env
    ports:
      - 3000:3000
    depends_on:
      - comms
      - auth
      - market
  
  comms:
    image: lucasignacio18/fakebook/comms-1.0
    restart: unless-stopped
    env_file:
      - docker/services/comms_service.env
    depends_on:
      - redis

  auth:
    image: lucasignacio18/fakebook/auth-1.0
    restart: unless-stopped
    env_file:
      - docker/services/auth_service.env
    expose:
      - 4444
    depends_on:
      - authdb

  market:
    image: lucasignacio18/fakebook/market-1.0
    restart: unless-stopped
    env_file:
      - docker/services/market_service.env
    expose:
      - 5555
    depends_on:
      - marketdb


  # Databases
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    expose:
      - 6379

  marketdb:
    image: mysql:5.7.20
    restart: unless-stopped
    env_file:
      - docker/dbs/marketdb.env

  authdb:
    image: mysql:5.7.20
    restart: unless-stopped
    env_file:
      - docker/dbs/authdb.env

  # Database admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
