version: "3"

services:

  # Microservices
  apigateway:
    build:
      context: ./api-gateway
    image: lucasignacio18/fakebook:api-gateway-1.0
    restart: unless-stopped
    env_file:
      - docker/services/apigateway.env
    ports:
      - 3000:3000
    depends_on:
      - chat
      - auth
      - market
      - users
  
  chat:
    build:
      context: ./chat
    image: lucasignacio18/fakebook:chat-1.0
    restart: unless-stopped
    env_file:
      - docker/services/chat_service.env
    depends_on:
      - redis

  auth:
    build:
      context: ./authentication
    image: lucasignacio18/fakebook:auth-1.0
    restart: unless-stopped
    env_file:
      - docker/services/auth_service.env
    expose:
      - 4444
    depends_on:
      - authdb

  market:
    build:
      context: ./market
    image: lucasignacio18/fakebook:market-1.0
    restart: unless-stopped
    env_file:
      - docker/services/market_service.env
    expose:
      - 5555
    depends_on:
      - marketdb

  users:
    build:
      context: ./users
    image: lucasignacio18/fakebook:users-1.0
    restart: unless-stopped
    env_file:
      - docker/services/market_service.env
    expose:
      - 6666
    depends_on:
      - usersdb

  # Databases
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    expose:
      - 6379

  marketdb:
    image: mysql:5.7.20
    restart: unless-stopped
    env_file:
      - docker/dbs/marketdb.env

  authdb:
    image: mysql:5.7.20
    restart: unless-stopped
    env_file:
      - docker/dbs/authdb.env

  usersdb:
    image: mysql:5.7.20
    restart: unless-stopped
    env_file:
      - docker/dbs/usersdb.env

  # Database admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
